import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SiteHeader from "@/components/header/header";
import Providers from "./providers";
import css from "./layout.module.css";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelTrucks",
  description: "Generated by CREATOR",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${css.html}`}>
      <body className={css.body}>
        <Providers>
          <div className={css.container}>
            <SiteHeader />
            <main className={css.main}>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
